---
stages:
  - test
  - downstream

molecule:
  image: registry.edc4it.com/cwdecks/delivery-management/awx/ansible-molecule
  stage: test
  script:
    - molecule test

rebuild-awx-ee:
  stage: downstream
  trigger: "../../awx-ee"
