---
image: docker:stable-dind

stages:
  - test
  - downstream

before_script:
  - apk add --no-cache
    python3 python3-dev py3-pip gcc git curl build-base
    autoconf automake py3-cryptography linux-headers
    musl-dev libffi-dev openssl-dev openssh
    rsync
  - docker info
  - python3 --version
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  - export PATH=/root/.cargo/bin/:$PATH
  - python3 -m pip install ansible molecule[docker] ansible-lint yamllint testinfra
  - ansible --version
  - molecule --version

molecule:
  stage: test
  script:
    - molecule test

rebuild-awx-ee:
  stage: downstream
  trigger: "../../awx-ee"
