---

- name: install minikube
  include_tasks: minikube.yml
  tags:
    - minikube
  when: minikube_version != "disabled"

- import_tasks: ./init.yaml

- name: install tools and utilities
  import_tasks: utilities.yaml
  tags:
    - utilities
