---
dependency:
  name: galaxy

driver:
  name: docker

# lint: |
#   set -e
#   yamllint .
#   ansible-lint

platforms:
  - name: ansible_role_minikube_default
    image: quay.io/centos/centos:stream8

provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml

verifier:
  name: testinfra
