---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ansible_role_setup_k8s
    image: quay.io/centos/centos:stream9
#    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
