---
- name: Install required software
  hosts: all
  tasks:

    - name: Install git
      ansible.builtin.package:
        name:
          - git
          - zsh

    - name: Ensure student exist with provided password
      ansible.builtin.user:
        name: student
        password: "{{ 'masterkey' | password_hash('sha512', 'mysecretsalt') }}"
        shell: "/bin/zsh"


