---
dependency:
  name: galaxy

driver:
  name: podman

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: ansible_role_minikube_default
    image: quay.io/centos/centos:stream8

provisioner:
  name: ansible

verifier:
  name: testinfra
