---
dependency:
  name: galaxy

driver:
  name: podman

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: ansible_role_minikube_default
    image: quay.io/centos/centos:stream9

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
  env:
    ANSIBLE_KEEP_REMOTE_FILES: 1

verifier:
  name: testinfra
