---
dependency:
  name: galaxy

driver:
  name: podman

lint: |
  set -e
  yamllint .
  ansible-lint

platforms:
  - name: ansible_role_minikube_default
    image: quay.io/centos/centos:stream8

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: debug
  # playbooks:
  #   prepare: prepare.yaml
  env:
    ANSIBLE_KEEP_REMOTE_FILES: 1  
    
verifier:
  name: testinfra
